name: CI

on:
  push:
    branches: [feature/**, fix/**, main]
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  platform-ci:
    uses: GitFabien/platform-demo-lab1/.github/workflows/ci-Quivront-Michel.yml@main